// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVN144GbJ9oyTJFesq2lYwlWEGxMS8Yk',
    appId: '1:462723129887:android:91c907fe42d310e0a0ab2a',
    messagingSenderId: '462723129887',
    projectId: 'test11505251',
    databaseURL: 'https://test11505251-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test11505251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVx_V-Di6N0IzHlmb0iL1_ubLIRy4QbQA',
    appId: '1:462723129887:ios:16419a50a736f00ea0ab2a',
    messagingSenderId: '462723129887',
    projectId: 'test11505251',
    databaseURL: 'https://test11505251-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test11505251.firebasestorage.app',
    androidClientId: '462723129887-0783krshdurd9gnpgq4v015t794ak0s8.apps.googleusercontent.com',
    iosClientId: '462723129887-8dfrp7n1eii6s4dq7auqlcg3fjnv0tnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruit1150608',
  );

}